spring.application.name=st-capstone-backend
server.error.whitelabel.enabled=false
logging.level.springframework=info


spring.datasource.url=jdbc:mysql://localhost:3308/test_capstone?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=1503
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true

riot.api.key=RGAPI-3c931837-e9fd-4e42-b441-82ddb581caa4
#riot.api.url=https://asia.api.riotgames.com